<?php

namespace ContainerIlxg776;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SbLJdY5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sbLJdY5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sbLJdY5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AdminController::allAdmin' => ['privates', '.service_locator.fmKhUTq', 'get_ServiceLocator_FmKhUTqService', true],
            'App\\Controller\\AdvantagesController::allAdvantages' => ['privates', '.service_locator.209vKPp', 'get_ServiceLocator_209vKPpService', true],
            'App\\Controller\\AppointmentController::allAppointment' => ['privates', '.service_locator.k8niE_K', 'get_ServiceLocator_K8niEKService', true],
            'App\\Controller\\AvailabilityController::allAdvantages' => ['privates', '.service_locator.sa2NCO6', 'get_ServiceLocator_Sa2NCO6Service', true],
            'App\\Controller\\CoachController::allCoach' => ['privates', '.service_locator.NWz6gvW', 'get_ServiceLocator_NWz6gvWService', true],
            'App\\Controller\\CoachController::getallPatients' => ['privates', '.service_locator.54rra3g', 'get_ServiceLocator_54rra3gService', true],
            'App\\Controller\\CourseController::allCourse' => ['privates', '.service_locator.J2Qh6MH', 'get_ServiceLocator_J2Qh6MHService', true],
            'App\\Controller\\PatientController::allPatient' => ['privates', '.service_locator.lVJkG_9', 'get_ServiceLocator_LVJkG9Service', true],
            'App\\Controller\\PatientController::getallPatients' => ['privates', '.service_locator.o.RTbA2', 'get_ServiceLocator_O_RTbA2Service', true],
            'App\\Controller\\PlanController::allPlan' => ['privates', '.service_locator.5ZCwxsA', 'get_ServiceLocator_5ZCwxsAService', true],
            'App\\Controller\\PlanningRulesController::allPlan' => ['privates', '.service_locator.XWu.50g', 'get_ServiceLocator_XWu_50gService', true],
            'App\\Controller\\PlanningRulesController::getPlanningById' => ['privates', '.service_locator.3YgwsAp', 'get_ServiceLocator_3YgwsApService', true],
            'App\\Controller\\TransactionController::allTransaction' => ['privates', '.service_locator.v57OW1I', 'get_ServiceLocator_V57OW1IService', true],
            'App\\Controller\\UsersController::allUser' => ['privates', '.service_locator.5AgJos5', 'get_ServiceLocator_5AgJos5Service', true],
            'App\\Controller\\UsersController::deleteUser' => ['privates', '.service_locator.3ddjjAN', 'get_ServiceLocator_3ddjjANService', true],
            'App\\Controller\\UsersController::getRoleById' => ['privates', '.service_locator.wYIawp6', 'get_ServiceLocator_WYIawp6Service', true],
            'App\\Controller\\UsersController::getUserById' => ['privates', '.service_locator.E2DLjxp', 'get_ServiceLocator_E2DLjxpService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\AdminController:allAdmin' => ['privates', '.service_locator.fmKhUTq', 'get_ServiceLocator_FmKhUTqService', true],
            'App\\Controller\\AdvantagesController:allAdvantages' => ['privates', '.service_locator.209vKPp', 'get_ServiceLocator_209vKPpService', true],
            'App\\Controller\\AppointmentController:allAppointment' => ['privates', '.service_locator.k8niE_K', 'get_ServiceLocator_K8niEKService', true],
            'App\\Controller\\AvailabilityController:allAdvantages' => ['privates', '.service_locator.sa2NCO6', 'get_ServiceLocator_Sa2NCO6Service', true],
            'App\\Controller\\CoachController:allCoach' => ['privates', '.service_locator.NWz6gvW', 'get_ServiceLocator_NWz6gvWService', true],
            'App\\Controller\\CoachController:getallPatients' => ['privates', '.service_locator.54rra3g', 'get_ServiceLocator_54rra3gService', true],
            'App\\Controller\\CourseController:allCourse' => ['privates', '.service_locator.J2Qh6MH', 'get_ServiceLocator_J2Qh6MHService', true],
            'App\\Controller\\PatientController:allPatient' => ['privates', '.service_locator.lVJkG_9', 'get_ServiceLocator_LVJkG9Service', true],
            'App\\Controller\\PatientController:getallPatients' => ['privates', '.service_locator.o.RTbA2', 'get_ServiceLocator_O_RTbA2Service', true],
            'App\\Controller\\PlanController:allPlan' => ['privates', '.service_locator.5ZCwxsA', 'get_ServiceLocator_5ZCwxsAService', true],
            'App\\Controller\\PlanningRulesController:allPlan' => ['privates', '.service_locator.XWu.50g', 'get_ServiceLocator_XWu_50gService', true],
            'App\\Controller\\PlanningRulesController:getPlanningById' => ['privates', '.service_locator.3YgwsAp', 'get_ServiceLocator_3YgwsApService', true],
            'App\\Controller\\TransactionController:allTransaction' => ['privates', '.service_locator.v57OW1I', 'get_ServiceLocator_V57OW1IService', true],
            'App\\Controller\\UsersController:allUser' => ['privates', '.service_locator.5AgJos5', 'get_ServiceLocator_5AgJos5Service', true],
            'App\\Controller\\UsersController:deleteUser' => ['privates', '.service_locator.3ddjjAN', 'get_ServiceLocator_3ddjjANService', true],
            'App\\Controller\\UsersController:getRoleById' => ['privates', '.service_locator.wYIawp6', 'get_ServiceLocator_WYIawp6Service', true],
            'App\\Controller\\UsersController:getUserById' => ['privates', '.service_locator.E2DLjxp', 'get_ServiceLocator_E2DLjxpService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\AdminController::allAdmin' => '?',
            'App\\Controller\\AdvantagesController::allAdvantages' => '?',
            'App\\Controller\\AppointmentController::allAppointment' => '?',
            'App\\Controller\\AvailabilityController::allAdvantages' => '?',
            'App\\Controller\\CoachController::allCoach' => '?',
            'App\\Controller\\CoachController::getallPatients' => '?',
            'App\\Controller\\CourseController::allCourse' => '?',
            'App\\Controller\\PatientController::allPatient' => '?',
            'App\\Controller\\PatientController::getallPatients' => '?',
            'App\\Controller\\PlanController::allPlan' => '?',
            'App\\Controller\\PlanningRulesController::allPlan' => '?',
            'App\\Controller\\PlanningRulesController::getPlanningById' => '?',
            'App\\Controller\\TransactionController::allTransaction' => '?',
            'App\\Controller\\UsersController::allUser' => '?',
            'App\\Controller\\UsersController::deleteUser' => '?',
            'App\\Controller\\UsersController::getRoleById' => '?',
            'App\\Controller\\UsersController::getUserById' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AdminController:allAdmin' => '?',
            'App\\Controller\\AdvantagesController:allAdvantages' => '?',
            'App\\Controller\\AppointmentController:allAppointment' => '?',
            'App\\Controller\\AvailabilityController:allAdvantages' => '?',
            'App\\Controller\\CoachController:allCoach' => '?',
            'App\\Controller\\CoachController:getallPatients' => '?',
            'App\\Controller\\CourseController:allCourse' => '?',
            'App\\Controller\\PatientController:allPatient' => '?',
            'App\\Controller\\PatientController:getallPatients' => '?',
            'App\\Controller\\PlanController:allPlan' => '?',
            'App\\Controller\\PlanningRulesController:allPlan' => '?',
            'App\\Controller\\PlanningRulesController:getPlanningById' => '?',
            'App\\Controller\\TransactionController:allTransaction' => '?',
            'App\\Controller\\UsersController:allUser' => '?',
            'App\\Controller\\UsersController:deleteUser' => '?',
            'App\\Controller\\UsersController:getRoleById' => '?',
            'App\\Controller\\UsersController:getUserById' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
