<?php

namespace ContainerFayVVHR;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_K0fMcHvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.k0fMcHv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.k0fMcHv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'availability' => ['privates', 'App\\Entity\\Availability', 'getAvailabilityService', true],
            'availabilityRepository' => ['privates', 'App\\Repository\\AvailabilityRepository', 'getAvailabilityRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'serializer' => ['services', '.container.private.serializer', 'get_Container_Private_SerializerService', true],
        ], [
            'availability' => 'App\\Entity\\Availability',
            'availabilityRepository' => 'App\\Repository\\AvailabilityRepository',
            'entityManager' => '?',
            'serializer' => '?',
        ]);
    }
}
