<?php

namespace ContainerFayVVHR;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0G9cN2bService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0G9cN2b' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0G9cN2b'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'coachRepository' => ['privates', 'App\\Repository\\CoachRepository', 'getCoachRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'patientRepository' => ['privates', 'App\\Repository\\PatientRepository', 'getPatientRepositoryService', true],
            'scheduleRepository' => ['privates', 'App\\Repository\\ScheduleRepository', 'getScheduleRepositoryService', true],
            'serializer' => ['services', '.container.private.serializer', 'get_Container_Private_SerializerService', true],
        ], [
            'coachRepository' => 'App\\Repository\\CoachRepository',
            'entityManager' => '?',
            'patientRepository' => 'App\\Repository\\PatientRepository',
            'scheduleRepository' => 'App\\Repository\\ScheduleRepository',
            'serializer' => '?',
        ]);
    }
}
