<?php

namespace ContainerFoQU26m;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAvailabilityService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Entity\Availability' shared autowired service.
     *
     * @return \App\Entity\Availability
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Entity/Availability.php';

        return $container->privates['App\\Entity\\Availability'] = new \App\Entity\Availability();
    }
}
