<?php

namespace ContainerKbOviLX;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3YgwsApService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3YgwsAp' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3YgwsAp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'planningRules' => ['privates', 'App\\Entity\\PlanningRules', 'getPlanningRulesService', true],
            'serializer' => ['services', '.container.private.serializer', 'get_Container_Private_SerializerService', true],
        ], [
            'planningRules' => 'App\\Entity\\PlanningRules',
            'serializer' => '?',
        ]);
    }
}
