<?php

namespace ContainerXyMimkI;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Hns9zUiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hns9zUi' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hns9zUi'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'scheduleRepository' => ['privates', 'App\\Repository\\ScheduleRepository', 'getScheduleRepositoryService', true],
            'serializerInterface' => ['services', '.container.private.serializer', 'get_Container_Private_SerializerService', true],
        ], [
            'scheduleRepository' => 'App\\Repository\\ScheduleRepository',
            'serializerInterface' => '?',
        ]);
    }
}
