<?php

namespace ContainerUbS3rHs;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5AgJos5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5AgJos5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5AgJos5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'AppUserRepository' => ['privates', 'App\\Repository\\AppUserRepository', 'getAppUserRepositoryService', true],
            'serializerInterface' => ['services', '.container.private.serializer', 'get_Container_Private_SerializerService', true],
        ], [
            'AppUserRepository' => 'App\\Repository\\AppUserRepository',
            'serializerInterface' => '?',
        ]);
    }
}
