<?php

namespace ContainerUbS3rHs;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Jylu4lGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Jylu4lG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Jylu4lG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'planningRulesRepository' => ['privates', 'App\\Repository\\PlanningRulesRepository', 'getPlanningRulesRepositoryService', true],
        ], [
            'entityManager' => '?',
            'planningRulesRepository' => 'App\\Repository\\PlanningRulesRepository',
        ]);
    }
}
