<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQxBk0a9\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQxBk0a9/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQxBk0a9.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQxBk0a9\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQxBk0a9\App_KernelDevDebugContainer([
    'container.build_hash' => 'QxBk0a9',
    'container.build_id' => '3e760d1b',
    'container.build_time' => 1700505058,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQxBk0a9');
