<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPTlbao5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPTlbao5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPTlbao5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPTlbao5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPTlbao5\App_KernelDevDebugContainer([
    'container.build_hash' => 'PTlbao5',
    'container.build_id' => 'd4b55481',
    'container.build_time' => 1702486420,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPTlbao5');
