<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_all_admin' => [[], ['_controller' => 'App\\Controller\\AdminController::allAdmin'], [], [['text', '/admin/all']], [], [], []],
    'app_all_advantages' => [[], ['_controller' => 'App\\Controller\\AdvantagesController::allAdvantages'], [], [['text', '/advantages/all']], [], [], []],
    'app_all_appointment' => [[], ['_controller' => 'App\\Controller\\AppointmentController::allAppointment'], [], [['text', '/appointment/all']], [], [], []],
    'app_all_availability' => [[], ['_controller' => 'App\\Controller\\AvailabilityController::allAdvantages'], [], [['text', '/availability/all']], [], [], []],
    'app_all_coach' => [[], ['_controller' => 'App\\Controller\\CoachController::allCoach'], [], [['text', '/coach/all']], [], [], []],
    'app_all_course' => [[], ['_controller' => 'App\\Controller\\CourseController::allCourse'], [], [['text', '/course/all']], [], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\HomePageController::index'], [], [['text', '/']], [], [], []],
    'app_all_patient' => [[], ['_controller' => 'App\\Controller\\PatientController::allPatient'], [], [['text', '/patient/all']], [], [], []],
    'patient_id' => [['id'], ['_controller' => 'App\\Controller\\PatientController::getallPatients'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/patient/all']], [], [], []],
    'app_all_plan' => [[], ['_controller' => 'App\\Controller\\PlanController::allPlan'], [], [['text', '/plan/all']], [], [], []],
    'app_all_planning_rules' => [[], ['_controller' => 'App\\Controller\\PlanningRulesController::allPlan'], [], [['text', '/planningrules/all']], [], [], []],
    'planning_id' => [['idPlanningRules'], ['_controller' => 'App\\Controller\\PlanningRulesController::getPlanningById'], [], [['variable', '/', '[^/]++', 'idPlanningRules', true], ['text', '/planningrules/all']], [], [], []],
    'app_all_transaction' => [[], ['_controller' => 'App\\Controller\\TransactionController::allTransaction'], [], [['text', '/transaction/all']], [], [], []],
    'app_all_user' => [[], ['_controller' => 'App\\Controller\\UsersController::allUser'], [], [['text', '/users']], [], [], []],
    'alluser_id' => [['id'], ['_controller' => 'App\\Controller\\UsersController::getRoleById'], [], [['text', '/roles'], ['variable', '/', '[^/]++', 'id', true], ['text', '/users']], [], [], []],
    'app_user_delete' => [['id'], ['_controller' => 'App\\Controller\\UsersController::deleteUser'], [], [['text', '/delete'], ['variable', '/', '[^/]++', 'id', true], ['text', '/users']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
];
